# Generated by Django 6.0.5 on 2026-05-24 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_payload', models.JSONField(help_text='Stores the exact raw source record/row')),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('NORMALIZED', 'Normalized'), ('VALIDATION_FAILED', 'Validation Failed')], default='UNPROCESSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('Scope 1', 'Scope 1 - Direct Emissions'), ('Scope 2', 'Scope 2 - Indirect Emissions (Electricity)'), ('Scope 3', 'Scope 3 - Other Indirect Emissions (Travel, etc.)')], max_length=10)),
                ('category', models.CharField(help_text='e.g. Diesel, Petrol, Electricity, Business Travel Flight', max_length=100)),
                ('activity_date', models.DateField(help_text='Normalized activity date')),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e_emissions', models.DecimalField(decimal_places=4, help_text='Emissions in kg CO2e', max_digits=18)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved & Locked'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked for audit after approval')),
                ('suspicious', models.BooleanField(default=False)),
                ('suspicious_reasons', models.JSONField(blank=True, default=list, help_text='Array of reasons why flagged suspicious')),
                ('validation_failed', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_record', to='ingestion.sourcerecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canonical_records', to='ingestion.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created Record'), ('EDIT', 'Edited Fields'), ('APPROVE', 'Approved & Locked'), ('REJECT', 'Rejected Record'), ('UNLOCK', 'Unlocked Record (Admin only)')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('canonical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.canonicalrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel CSV Export'), ('UTILITY_ELECTRICITY', 'Utility Electricity Portal Export'), ('TRAVEL_JSON', 'Corporate Travel JSON API/File')], max_length=50)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='canonicalrecord',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_records', to='ingestion.uploadbatch'),
        ),
    ]
